Added debug log in terr apply

diff --git a/.github/workflows/ci-cd.yaml b/.github/workflows/ci-cd.yaml
--- a/.github/workflows/ci-cd.yaml
+++ b/.github/workflows/ci-cd.yaml
@@ -77,11 +77,17 @@ jobs:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           AWS_DEFAULT_REGION: us-east-1
+          TF_LOG: DEBUG
         run: |
+          echo "Running terraform apply..."
           terraform -chdir=Terraform apply -auto-approve \
           -var="key_name=${{ env.KEY_NAME }}" \
           -var="public_key=${{ env.PUBLIC_KEY }}" \
           -var="private_key_path=private.pem"
+
+          echo "-----TERRAFORM DEBUG LOG START-----"
+          cat terraform-debug.log || echo "Debug log not found"
+          echo "-----TERRAFORM DEBUG LOG END-----"
 
   kubernetes:
     needs: IAC
